NAME = megaphone

CPP = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

SRC = megaphone.cpp

all : $(NAME)

$(NAME) :
	$(CPP) $(FLAGS) $(SRC) -o $(NAME)

clean :
	rm -rf $(NAME)

fclean :
	rm -rf $(NAME)

re : fclean all